import Head from "next/head";
// import Image from "next/image";

import { Avatar, Button, Typography } from "@material-ui/core";

import styled from "styled-components";
import Link from "next/link";
import { NextPage } from "next";
import { useEffect, useState } from "react";

import {
  collection,
  Firestore,
  getDocs,
  Query,
  QueryDocumentSnapshot,
  QuerySnapshot,
} from "firebase/firestore";
import { User } from "@/types";

import db from "@/utils/firebase";
import { useUserContext } from "@/components/user-context";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter()
  const [users, setUsers] = useState<User[]>();
  const { setUserContext } = useUserContext();

  useEffect(() => {
    const getUsers = async () => {
      const q = collection(db, "users");

      const querySnapshot = await getDocs(q);
      const docs = querySnapshot.docs;
      const data: User[] = docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));

      if (data) {
        console.log(data);
        setUsers(data);
      }
    };

    getUsers();
  }, []);

  const hanleClick = (id: string) => {
    setUserContext({
      currentUser: users?.find((user) => user.id === id),
      contacts: users?.filter((user) => user.id !== id),
    });

    router.push("/dashboard")
  };

  return (
    <>
      <Head>
        <title>Chat App</title>∏
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <img
          src="https://crystallize.com/static/logo/crystallize-logo.svg"
          alt=""
        />
        <Typography variant="h4" gutterBottom>
          chat
        </Typography>

        <Typography gutterBottom>login as</Typography>
        {/* <Link href="/dashboard">
          <Button>Login</Button>
        </Link> */}

        <AvatarWrapper>
          {users?.map(({ name, avatarUrl, id }) => (
            <AvatarHug onClick={() => hanleClick(id)}>
              <Avatar
                alt={name}
                src={avatarUrl}
                style={{
                  boxShadow: "4px 4px 24px 0px rgba(0, 0, 0, 0.45)",
                  height: "100%",
                  width: "100%",
                }}
              />
            </AvatarHug>
          ))}
        </AvatarWrapper>
      </Wrapper>
    </>
  );
};

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100%;
`;

const AvatarWrapper = styled.div`
  display: grid;
  grid-template-columns: repeat(3, auto);
  grid-gap: 16px;
  height: 64px;
`;

const AvatarHug = styled.div`
  cursor: pointer;
  height: 56px;
  width: 56px;
  transition: 0.3s;

  &:hover {
    height: 64px;
    width: 64px;
  }
`;

export default Home;
