import Head from "next/head";

import { Avatar, Typography } from "@material-ui/core";

import styled from "styled-components";

import { NextPage } from "next";

import { useUserContext } from "@/components/user-context";
import { useRouter } from "next/router";
import Image from "next/image";
import { useCallback } from "react";

const Home: NextPage = () => {
  const router = useRouter();

  const { setCurrenttUser, allUsers } = useUserContext();

  const hanleClick = useCallback(
    (id: string) => {
      const selectedUser = allUsers!.find((user) => user.id === id)!;

      setCurrenttUser(selectedUser);
      localStorage.setItem("currentUserID", selectedUser.id.toString());

      router.push("/dashboard");
    },
    [allUsers, router, setCurrenttUser]
  );

  return (
    <>
      <Head>
        <title>Chat App</title>∏
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Image
          src="https://crystallize.com/static/logo/crystallize-logo.svg"
          width={251}
          height={85}
          alt="Crystallize logo"
        />
        <Typography variant="h4" gutterBottom>
          chat
        </Typography>

        <Typography gutterBottom>login as</Typography>

        <AvatarWrapper>
          {allUsers?.map(({ name, avatarUrl, id }) => (
            <AvatarHug onClick={() => hanleClick(id)} key={id}>
              <Avatar
                alt={name}
                src={avatarUrl}
                style={{
                  boxShadow: "4px 4px 24px 0px rgba(0, 0, 0, 0.45)",
                  height: "100%",
                  width: "100%",
                }}
              />
            </AvatarHug>
          ))}
        </AvatarWrapper>
      </Wrapper>
    </>
  );
};

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100%;
`;

const AvatarWrapper = styled.div`
  display: grid;
  grid-template-columns: repeat(4, auto);
  grid-gap: 16px;
  height: 64px;
`;

const AvatarHug = styled.div`
  cursor: pointer;
  height: 56px;
  width: 56px;
  transition: 0.3s;

  &:hover {
    height: 64px;
    width: 64px;
  }
`;

export default Home;
